### ISSUE TITLE
Modern CPU Adaptation

### ISSUE THREAD

**Issue by sargentomili** [faster-cpython/ideas#460] opened 2022-09-16 08:22 UTC
I am wonder why dont take advantage from modern multicore CPU.

Now we usually have plenty of cores  in our CPU, why dont look how many aviables at the start of python program and adapt it to that, for example in the case you have more than one core, in parallel with the execution you can make run the compilation or optimization in other cores, or try to detect codes with highly benefits of parallelizing and automatically optimize for it (i.e some types of loops. In the for-each with lists or arrays you can even see how many loops proabbly you will do).

It could be a problem about % of CPU use unintentionaly, but as defoult/or in this process you could have it limitated i.e to dont surpass 25% of use or 25% of cores.

**Comment by gvanrossum** [comment] 2022-09-16 14:42
We’re well aware. The issue is what specifically to do. Closing this issue as too general.

**Closed by gvanrossum** 2022-09-16 14:42 UTC
